### ISSUE TITLE
Feature Request to add Update and Delete functions to Sync

### ISSUE THREAD

**Issue by henryhardy** [SyncDB/Sync#162]
Hello =]

I love your framework, and would like it to become the one stop shop style thing for all of your CoreData needs. Currently though, it's obviously designed mainly around the 'Sync' functionality it's named after. 

For example, if I were to want to just delete an entry, currently I'm not able to do that in Sync. Given the beautiful syntax and ease of use, use of background threads etc, it would be great for Sync to include that too. (Unless i'm a noob and just totally missed something)

Suggested changes would be just expanding on the functions so you could go 

Sync.delete([primaryKey],
  inEntityNamed: String!,
  dataStack: DATAStack!,
  completion: ((NSError!) -> Void)!)

which would delete the record/s with that primary key/s.  and it's related entities if there are any.

Also good would be to add into sync changes an option to switch between replace and update, as well as if unfound records are deleted, so it would be something like

Sync.delete([primaryKey],
  inEntityNamed: String!,
 deleteMissingRecords: Bool,
 updateRecords: Bool,
  dataStack: DATAStack!,
  completion: ((NSError!) -> Void)!)

where update records would be a true update, not a delete and replace, which is what Sync seems to currently do.

Also, (this could be asking for too much =P) A Sync Fetch would be great. Basically just the same as
as standard NSFetchRequests, but Sync-ified so something like..

Sync.fetch( inEntityNamed: String!,
 predicate: predicate,
  dataStack: DATAStack!,
  completion: ((NSError!) -> Void)!)

Sync is fantastic, and even using normal FetchRequests to get and save is still great. I understand that we could fetch, then pass it back into Sync, but that takes you into vanilla code, and yours is tastier to use. If this is something you would like help on let me know.

**Comment by 3lvis** [comment]
Hi Henry,

Thanks for writing us, it's great to hear that you like Sync, I use it in all my projects :grin:! 

I've been thinking on how to expand the functionality for the rest of methods, your proposal for delete makes a lot of sense and looks beautiful btw.

Regarding:
>where update records would be a true update, not a delete and replace, which is what Sync seems to currently do.

I guess having a separate `update` method could work here instead of adding more complexity to the main Sync method.

Finally, Sync fetch sounds awesome! I already have something like that in place in my private repos and works quite well.

I'll make individual tasks for this items so we can keep progress on each.

Thanks again, ❤ :bouquet:

**Comment by 3lvis** [comment]
Insert would be cool, too.

**Comment by rafalwojcik** [comment]
@henryhardy You can do delete uding data stack, to prevent deleting objects that don't exist in JSON use method swizzling like this:
```
import Foundation
import CoreData
import DATAFilter

extension DATAFilter {

    override public class func initialize() {
        struct Static {
            static var token: dispatch_once_t = 0
        }
        dispatch_once(&Static.token) {
            let originalSelector = #selector(DATAFilter.changes(_:inEntityNamed:predicate:operations:localKey:remoteKey:context:inserted:updated:))
            let swizzledSelector = #selector(DATAFilter.swizzled_changes(_:inEntityNamed:predicate:operations:localKey:remoteKey:context:inserted:updated:))
            let originalMethod = class_getClassMethod(self, originalSelector)
            let swizzledMethod = class_getClassMethod(self, swizzledSelector)
            method_exchangeImplementations(originalMethod, swizzledMethod)
        }
    }

    class func swizzled_changes(changes: [AnyObject]!, inEntityNamed entityName: String!, predicate: NSPredicate!, operations: DATAFilterOperation, localKey: String!, remoteKey: String!, context: NSManagedObjectContext!, inserted: (([NSObject : AnyObject]!) -> Void)!, updated: (([NSObject : AnyObject]!, NSManagedObject!) -> Void)!) {
        DATAFilter.swizzled_changes(changes, inEntityNamed: entityName, predicate: predicate, operations: [.Insert, .Update], localKey: localKey, remoteKey: remoteKey, context: context, inserted: inserted, updated: updated)
    }
}
```

**Comment by 3lvis** [comment]
Hi @rafalwojcik,

Thanks for adding this. I think it's enough requests for me to consider adding this requests. I'll do it in the following days.

You are awesome :bouquet: 

![gif-dave-grohl-thank-you-thanks-gif](https://cloud.githubusercontent.com/assets/1088217/14016112/40aa26f2-f1be-11e5-8dd7-7b02a7dc67e4.gif)

**Comment by rafalwojcik** [comment]
@3lvis since DATAFilter change implementation witch version change here you have actual code:
```
import Foundation
import CoreData
import DATAFilter

extension DATAFilter {

    override public class func initialize() {
        struct Static {
            static var token: dispatch_once_t = 0
        }
        dispatch_once(&Static.token) {
            let originalSelector = #selector(DATAFilter.changes(_:inEntityNamed:predicate:operations:localPrimaryKey:remotePrimaryKey:context:inserted:updated:))
            let swizzledSelector = #selector(DATAFilter.swizzled_changes(_:inEntityNamed:predicate:operations:localPrimaryKey:remotePrimaryKey:context:inserted:updated:))
            let originalMethod = class_getClassMethod(self, originalSelector)
            let swizzledMethod = class_getClassMethod(self, swizzledSelector)
            method_exchangeImplementations(originalMethod, swizzledMethod)
        }
    }

    class func swizzled_changes(changes: [AnyObject]!, inEntityNamed entityName: String!, predicate: NSPredicate!, operations: DATAFilterOperation, localPrimaryKey: String!, remotePrimaryKey: String!, context: NSManagedObjectContext!, inserted: (([NSObject : AnyObject]!) -> Void)!, updated: (([NSObject : AnyObject]!, NSManagedObject!) -> Void)!) {
        DATAFilter.swizzled_changes(changes, inEntityNamed: entityName, predicate: predicate, operations: [.Insert, .Update], localPrimaryKey: localPrimaryKey, remotePrimaryKey: remotePrimaryKey, context: context, inserted: inserted, updated: updated)
    }
}
```

**Comment by 3lvis** [comment]
Working on a way to specify Sync operations. https://github.com/hyperoslo/Sync/pull/223

**Comment by 3lvis** [comment]
Fetch and delete should be coming soon. But if someone feels like it, feel free to submit a PR.

#### Delete
```swift
//  deletedKeys could be strings or numbers
public class func delete(primaryKeys: [AnyObject], inEntityNamed entityName: String, dataStack: DATAStack, completion: ((error: NSError?) -> Void)?) {
    // ....
}
```

#### Fetch

```swift
// primaryKeys could be strings or numbers
// synchronous method, it runs in the same thread that is called
// could also use generics instead of `[NSManagedObject]
public class func fetch(primaryKeys: [AnyObject], inEntityNamed entityName: String, context: NSManagedObjectContext) -> [NSManagedObject] {
    // ....
}
```

**Comment by 3lvis** [comment]
Added operation types in 1.9.0

https://github.com/hyperoslo/Sync/releases/tag/1.9.0

**Comment by FrancisBehnen** [comment]
Shouldn't did be closed as resolved?

**Comment by 3lvis** [comment]
I guess this issue was too big and covered lots of stuff. One part of the issue was fixed, adding operations, but having different methods for `delete` and `fetch` haven't being implemented yet.

**Comment by 3lvis** [comment]
Fixed in https://github.com/SyncDB/Sync/pull/332

**Comment by 3lvis** [comment]
If you have any feedback regarding the API let me know ❤️

**Comment by 3lvis** [comment]
# Current API

## Insert
```swift
try! Sync.insertOrUpdate(["id": "id", "name": "name"], inEntityNamed: "User", using: context)
```
