### ISSUE TITLE
Blog post on why this is useful?

### ISSUE THREAD

**Issue by AndrewSB** [SyncDB/Sync#268]
This library looks great, but Im not all that familiar with the reasons you'd want to parse JSON -> Core data. Are there any good resources that would inform me of the best practices on this? Has @hyperoslo put out anything?

Assuming its related to having a local cache on device, but nevertheless, I think having something like this would be super helpful for anyone looking at the README

**Comment by 3lvis** [comment]
Good idea. I'll see what we can do.

**Comment by AndrewSB** [comment]
Awesome 🙃

**Comment by 3lvis** [comment]
Expanded a bit on the [README](https://github.com/SyncDB/Sync/blob/master/README.md), I'll consider adding more in the future meanwhile you might find this informative.

https://github.com/3lvis/Dream

**Comment by AndrewSB** [comment]
I see the value now.
Thank you for building this 😊
