### ISSUE TITLE
Third level nested objects are not being created

### ISSUE THREAD

**Issue by normand1** [SyncDB/Sync#271]
## Problem Description

I created a simplified project to demonstrate the issue I'm seeing. I have a json object I'm importing from a file named `global-nested-users.json`. I'm using Sync to create Core Data objects from the json like this:

```
Sync.changes(json["user_model"] as! Array, inEntityNamed: "UserModel", dataStack: AppDelegate.sharedDataStack(), operations: [.Insert, .Update], completion: { error in })`
```

In the completion block I print out all user objects expecting to see both my top level UserModels and my nested UserModels, but I am only seeing my top level UserModels.

```
let userModels = try         
AppDelegate.sharedDataStack().mainContext.executeFetchRequest(fetchRequest)

        for model in userModels as! [UserModel] {
            print("username: \(model.userName!)")
        }
```

However, I only see my top level user's printed:

```
username: userName1
username: userName2
```
### Json Model

I have 2 core data objects AccountModel and UserModel. I am trying to use Sync to create UserModel and AccountModel objects from JSON with this structure:

```
{
  "user_model": 
   [
     {
      "user_name": "userName1",
      "id" : "0",
      "user_owned_account" :
      {
        "id" : "1",
        "account_name" : "accountName1",
        "second_owner" :
         {
           "id" : "3",
           "user_name" : "deepUser1"
         }
       }
     },
     {
      "user_name": "userName2",
      "id" : "1",
      "user_owned_account" :
      {
        "id" : "2",
        "account_name" : "accountName2",
        "second_owner" :
          {
            "id" : "4",
            "user_name" : "deepUser2"
          }
       }
      } 
    ]
} 
```
### Core Data Model

![screen shot 2016-08-30 at 1 46 16 pm](https://cloud.githubusercontent.com/assets/1393261/18106341/28cf7768-6eb8-11e6-9465-bfec5e798285.png)
### Possible Solution ???

After debugging I came to the conclusion that the issue might be in this method:

```
  func sync_fillWithDictionary(dictionary: [String : AnyObject], parent: NSManagedObject?, dataStack: DATAStack, operations: DATAFilterOperation) {
```

...

```
  } else if let parent = parent where !parent.isEqual(valueForKey(relationship.name)) && relationship.destinationEntity?.name == parent.entity.name {
```

...

I modified the above line to what's below and it fixed my issue. However, I'm not sure what the side effects of this change might be and would like to know if there is a better change I could make.

```
 } else if let parent = parent where !parent.isEqual(valueForKey(relationship.name)) && relationship.destinationEntity?.name == parent.entity.name ***&& valueForKey(relationship.name) != nil*** {
```
### Issue Example Project

This project demonstrates the issue I've detailed above:
https://github.com/normand1/SyncIssueExampleProject

**Comment by 3lvis** [comment]
Thanks a lot for providing such detailed bug report! I'm quite busy this week, I'm sorry if I don't have a look earlier.

**Comment by 3lvis** [comment]
Hi @normand1!

I hope you're doing fine, it's been a long time since this issue. Looks like this was fixed in a previous release, added a unit test and everything seems working like it should.

https://github.com/SyncDB/Sync/pull/351

Hugs.
