### ISSUE TITLE
Syncing super entities with "To many" in both ways

### ISSUE THREAD

**Issue by dersvenhesse** [SyncDB/Sync#277]
I just run into an issue when syncing super entities and tried to find the error when comparing my model to the test case for #239.

In the test case `Car` to `Passenger` is a To-Many-Relation, the inverse is a To-One-Relation. Now when using a To-Many-Relation for the inverse as well, the function `testBug239()` fails since there are now passengers in the first racecar.

Is there a way to get around this problem? Or does the syncing functionality with super entities only apply for relations as in the test case?

Thanks in advance.

**Comment by 3lvis** [comment]
Noted, I'll see if I can reproduce it.

**Comment by 3lvis** [comment]
Thanks a lot for reporting this issue, sadly at the moment I'm really busy at work. Hopefully I'll get time to have a look at this issue early next week, I hope that's ok for you. Have a good weekend!

But as always PRs are very welcome, if there's something hard to understand I can take some time to give some guidance.

**Comment by 3lvis** [comment]
I was able to reproduce this issue. Unit test here -> https://github.com/SyncDB/Sync/pull/350

**Comment by 3lvis** [comment]
Fixed in https://github.com/SyncDB/Sync/pull/350
