### ISSUE TITLE
NSPersistentContainer

### ISSUE THREAD

**Issue by cflorion** [SyncDB/Sync#284]
Hi,

My new app uses NSPersistentContainer for its core data stack. I want to use Sync to communicate with my API.

The thing is that I noticed that Sync is tightly coupled with DataStack. I am looking into recoding part of Sync so it used NSPersistentContainer contexts, or maybe there is a way to pass NSPersistentStoreContainer's contexts to DataStack ?

But maybe this is a bad idea, this coupling must exist for a reason. I think NSPersistentContainer's contexts use the parent/child relation for context, but not DataStack. Maybe that could break Sync ?

I don't know what to think, have you got any thoughts on this @3lvis ?
Have a nice day everyone ;)

**Comment by 3lvis** [comment]
Hi! OMG. You're already iOS 10 only? 

I haven't had the chance to look at this closely, but there's the chance to make it work, although we could lose some features.

Is there a reason on why you're using `NSPersistentContainer` instead of something like `DATAStack`?

**Comment by cflorion** [comment]
Yes, iOS 10 only :)
All our B2B users update their OS quickly 👌🏻 #lucky

No wise reason to use `NSPersistentContainer ` no. Only that the more code in Apple's hands is less code in mine (and less bugs hopefully).

But that's probably a wrong reason. I noticed that `DATAStack` dont use parent/child context, is there reason for that ?

**Comment by 3lvis** [comment]
Main reasoning for decoupling so far has been that owning the entire stack means it's easier to fix any potential issues. In theory it should be able to work with `NSPersistentContainer`.

**Comment by 3lvis** [comment]
`parent/child` context have been really buggy for me in the past. Meanwhile merging has been more stable. Also then I'm able to do this: https://github.com/3lvis/SyncPerformance aka loading tons of tons of objects into Core Data without blocking the UI since there's no merging into the main thread.

**Comment by cflorion** [comment]
I see, good point. I'll give `DATAStack`a try right now.
Thanks 3lvis!

**Comment by 3lvis** [comment]
🎉 Let's keep this task open, would be awesome to try Sync with NSPersistentContainer.

**Comment by RolandasRazma** [comment]
@3lvis you could use https://github.com/inspace-io/INSPersistentContainer for now to support it on lower iOS versions. Logic would be: replace DATAStack with INSPersistentContainer for now. Remove INSPersistentContainer dependancy when dropping support for iOS9 later

**Comment by 3lvis** [comment]
@RolandasRazma sounds smart!

**Comment by 3lvis** [comment]
Added basic support for `NSPersistentContainer` in theory Sync could be used with just a NSManagedObjectContext.

**Comment by 3lvis** [comment]
The main issue is that using DATAStack lowers down the amount of support since we have more control over the Core Data stack.
