### ISSUE TITLE
[Feature Request] Sync.changes for specific object.

### ISSUE THREAD

**Issue by RolandasRazma** [SyncDB/Sync#297]
it might be hard to understand flow I'm trying to achieve, but let me try to explain :)

**Flow (pseudo code):**
```swift
let context = dataStack.newBackgroundContext() // allocate context

let newMO = MO(inContext: context) // create new NSManagedObject
newMO.somePropery = "TEST" // assign new value

let newMOJSONRepresentation = newMO.hyp_dictionary() // convert whole object to "JSON"

// send just created objects representation to server
Server.sendObject(newMOJSONRepresentation) { updatedJSON: JSON in
    // server returns new data. Data is for this particular object.
    Sync.changes(updatedJSON, object: newMO) // apply returned data to object
}
```

**Problem:**
there is no way of doing this in vanilla Sync. 
I managed to implement this by copying whole `Sync.changes` wrapping it in `performIn...`, removing `DATAFilter.changes` lookup and just doing `newMO.sync_fillWithDictionary` but it looks messy.

**Challenges:**
`Server.sendObject` is escaping so `NSManagedObjectContext` needs to be retained. Its unclear where to get `entityName` from...

**Thoughts:**
Maybe my thinking is completely wrong and I'm doing something Im not supposed to?

**Comment by 3lvis** [comment]
@RolandasRazma Great suggestion! I of course see how this could be useful.

**Comment by 3lvis** [comment]
I really need to remove this

```swift
let context = dataStack.newBackgroundContext() // allocate context
```

Background contexts are really meant to be used using `performBlock` or `performBlockAndWait`

**Comment by 3lvis** [comment]
@RolandasRazma there's already this

```
let userJSON = JSON["user"]
user.hyp_fill(with: userJSON)
```

From Sync's dependency [SYNCPropertyMapper](https://github.com/SyncDB/SYNCPropertyMapper).

I think it would fill your needs. Let me know otherwise.
