### ISSUE TITLE
Sync changes

### ISSUE THREAD

**Issue by ro22e0** [SyncDB/Sync#298]
Hello,
I there a way to choose if it include subentities when perform changes ?

**Comment by 3lvis** [comment]
Hi @ro22e0,

How would you normally do that? I'm not sure if we have support for that.

**Comment by ro22e0** [comment]
"includesSubentities" a property of NSFetchRequest and the default value is true.

Here : [Apple doc](https://developer.apple.com/reference/coredata/nsfetchrequest/1506366-includessubentities)

**Comment by 3lvis** [comment]
@ro22e0 that's not supported at the moment but should be possible to add it.

Could you please share your use case (Core Data model + JSON) to reproduce it?

**Comment by ro22e0** [comment]
Yes I'll reopen it when it done
