### ISSUE TITLE
No such module 'NSEntityDescription_SYNCPrimaryKey'

### ISSUE THREAD

**Issue by Sorix** [SyncDB/Sync#299]
I'm installing Sync with that pod (for Swift 2.3):
`	pod 'Sync', '~> 1'`

I receive an error when trying to build:
`/Pods/Sync/Source/NSManagedObject+Sync.swift:2:8: No such module 'NSEntityDescription_SYNCPrimaryKey'`

```swift
import CoreData
import NSEntityDescription_SYNCPrimaryKey // error here
import DATAStack
import NSString_HYPNetworking
import DATAFilter
```

**Comment by PiotrOlszewski** [comment]
I had exactly the same problem:

Pods combination:

  pod 'Alamofire', '3.5.0'
  pod 'Sync', '1.14.3'
  pod 'NSManagedObject-HYPPropertyMapper', '4.1.1'
  pod 'DateParser', '0.1.0'

works for me as a temporary fix :)

Hope it helps.

**Comment by 3lvis** [comment]
Can you try again? The latest release should fix this problem.

https://github.com/SyncDB/Sync/releases/tag/1.15.0

**Comment by 3lvis** [comment]
Let me know if I should re-open this issue. Thanks for reporting it!
