### ISSUE TITLE
Support for date formatting or add date format: 2016-10-10 07:00:00

### ISSUE THREAD

**Issue by klivin** [SyncDB/Sync#300]
Need support for date format: "2016-10-10 07:00:00"

Could you add ability to assign our own date formatter, or could you add the above formatting?

**Comment by 3lvis** [comment]
Hi @klivin,

It's possible to add your own formatting.

https://github.com/SyncDB/NSManagedObject-HYPPropertyMapper/blob/master/Tests/NSManagedObject%2BHYPPropertyMapper/HYPFillWithDictionaryTests.m#L173

But the format that you requested is in the list as well.

https://github.com/SyncDB/DateParser/issues/4

**Comment by klivin** [comment]
That's great, I would like to add my own formatter, trying what you put in your docs: 
https://github.com/SyncDB/NSManagedObject-HYPPropertyMapper#dates

However, the link to the example is broken where it says:
You can find an example of date transformer in DateStringTransformer.

Getting a not found error.
I am left wondering what DateStringTransformer should look like?

**Comment by 3lvis** [comment]
Link fixed!

**Comment by klivin** [comment]
Hi there, I am trying to get dates mapping using ValueTransformer in Swift 3.

I register the ValueTransformer as such:
```
       ValueTransformer.setValueTransformer(DateStringTransformer(),
                                             forName: NSValueTransformerName(rawValue: "DateStringTransformer"))
```
Here's my actual transformer:
```

import Foundation

class DateStringTransformer : ValueTransformer {
    override class func transformedValueClass() -> AnyClass {
        return Date.self as! AnyClass
    }
    
    override class func allowsReverseTransformation() -> Bool {
        return false
    }
    
    override func transformedValue(_ value: Any?) -> Any? {
        guard let setvalue = value as? String else {
            return value
        }
        let date = DateFormatter.utcDateFormatter().date(from: setvalue)
        print("transformed date \(date)")
        return date
    }
    
}

```
The transformed date is getting returned with a valid date when Sync starts mapping i see output:
transformed date 2016-10-11 15:30:00 +0000
transformed date 2016-10-11 07:00:00 +0000
...

However, Sync will crash on context.save() (Sync.swift line 242)  with the stack trace:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSTaggedDate bytes]: unrecognized selector sent to instance 0xe41bdad3cf800000'

If I print out the object it is looking at, it's a Date??
po 0xe41bdad3cf800000
2016-10-11 15:30:00 +0000

(lldb) po [0xe41bdad3cf800000 class]
__NSTaggedDate

Please let me know if you see anything obvious I am missing

**Comment by 3lvis** [comment]
Hi @klivin,

I'm sorry for not looking at this before, quite busy at work. As a workaround I would recommend you to pre-process your JSON to have ISO 8601 dates. I'll try to put some time later this week to fix the issues that you mentioned.

Best,

**Comment by 3lvis** [comment]
@klivin Hi, I took a second look and added a demo on how value transformers should be used. Basically, you need to add a key to your User Info. I would recommend to not use Transformables since they don't seem very reliable.

https://github.com/SyncDB/SYNCPropertyMapper#dealing-with-bad-apis

**Comment by 3lvis** [comment]
Moved to https://github.com/SyncDB/SYNCPropertyMapper/issues/134

**Comment by 3lvis** [comment]
Fixed here https://github.com/SyncDB/SYNCPropertyMapper/pull/135
