### ISSUE TITLE
Entity duplicated if ignored from Sync.changes using predicate

### ISSUE THREAD

**Issue by allemattio** [SyncDB/Sync#301]
Hi,

I'm having an issue in my app.
I use a predicate to exclude some entities from the sync, in my case are entities modified on the app that need to be sent to the server before pulling the new entities from server, so the predicates and the Sync.changes methods look like this:

```
let predicate = NSPredicate(format: "synced = true", argumentArray: nil)
               
Sync.changes([json data array from server], inEntityNamed: "myEntityName", predicate: predicate, dataStack: self.dataStack) { error in
}
                
```
What happens is that if in the JSON to Sync that arrives from the Server is present an entity with the same id(the field I use as primary key with the flag hyper.isPrimaryKey) as one of the Entities ignored using the predicate, this entity gets inserted and I will have a duplicated entity.

In my head in this case this entities should be ignored also from the incoming JSON, not inserted in the DB if is already present a record with my specified primaryKey.
I see that in the DB is used another column as "real" primary key.
I need to perform both Delete, Insert and Update operation in this Sync so I can't exclude the Insert.

Is there a way to solve this problem?
Thanks in advance

**Comment by Proper-Job** [comment]
@allemattio I think what you're describing is actually a valid use case.
One thing I noticed though is that I believe you have a syntax error in your predicate format string. I think equality testing should be done with two equal signs ``==`` as described [here](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Predicates/Articles/pCreating.html#//apple_ref/doc/uid/TP40001793-SW4).

I agree with you that in some cases it can be necessary (imperative even) that certain objects be excluded from any INSERT, UPDATE, DELETE operations. 
In my understand Sync uses the mapping predicate is like this: 

> Compare the server payload to the objects in the local database retrieved through the specified predicate. Perform INSERT, UPDATE, DELETE as necessary by comparing the server object ids to the device object ids.

It would be great if Sync exposed an exclude predicate that amends the functionality like this: 

> Do the mapping as described above, but exclude objects retrieved through the exclude predicate from all mapping operations.

That way objects in the device database that have been altered on the device can be protected from inadvertent changes.

I'm not sure if Sync already provides this functionality. I don't [specifying the mapping operations](https://github.com/SyncDB/Sync#what-if-i-only-want-inserts-and-updates) completely covers this situation.

@3lvis what are your thoughts on this?

**Comment by 3lvis** [comment]
I think this is related to this https://github.com/SyncDB/Sync/pull/189

Basically today we run the predicate through the local/Core Data objects. Ideally we should also run the predicate through the JSON file, so we make sure that all objects (remote and local) are ignored if they don't comply with the predicate.

**Comment by Proper-Job** [comment]
@3lvis that won't have the same effect as an exclude predicate.  
In the example above all local objects with ``synced == FALSE`` should be excluded from any mapping operations. What if the field ``synced`` isn't present in the server payload, or is always ``true``?  Wouldn't the local objects still be overwritten?

**Comment by 3lvis** [comment]
@Proper-Job You're right, for that use case at the moment in one of my apps I take the JSON and take the IDs as an array.

```swift
let ids = (items as NSArray).value(forKey: "id") as? [String] ?? [String]()
let predicate =  NSPredicate(format: "id IN %@ AND synced == true", ids)
```

This would mean, sync this JSON, excluding all the attributes marked as true, and at the same time, exclude all the items that have one of this IDs.

**Comment by Proper-Job** [comment]
@3lvis I don't actually see how taking the ids from the JSON payload into the predicate will help avoid inadvertent overwriting of local objects.  I'll sketch out an example to illustrate what I mean.

Let's say I have the following CoreData model:

```swift
public class ToDo: NSManagedObject {
    @NSManaged public var id: NSNumber?
    @NSManaged public var name: String?
    @NSManaged public var completed: NSNumber?
    @NSManaged public var inProgress: NSNumber?
}
```

And the following JSON payload that comes from the server:

```json
[
	{
		"id": 1,
		"name": "Go shopping",
		"completed": false
	},
	{
		"id": 2,
		"name": "Do the washing up",
		"completed": false
	},
	{
		"id": 3,
		"name": "Buy flowers for your girlfriend",
		"completed": false
	}
]
```

Now let's say I've synced my todos to the app and I'm on my way to buy flowers for my girlfriend.  I set the ``inProgress`` flag to ``true`` in the app.  That gives me the following states in my CoreData model instances:

```
NSManagedObject(id=1,name='Go shopping',completed=false,inProgress=false)
NSManagedObject(id=2,name='Do the washing up',completed=false,inProgress=false)
NSManagedObject(id=3,name='Buy flowers for your girlfriend',completed=false,inProgress=true)
```

Let's say I now Sync.changes again with the predicate you suggested:

```swift
// JSON ids == [1,2,3]
let ids = (json as NSArray).value(forKey: "id") as? [String] ?? [String]()
// fetched ids == [1,2]
let predicate =  NSPredicate(format: "inProgress == FALSE AND id IN %@", ids)
```

If I understand the underlying mapping algorithm correctly this should result in the server objects with ids = [1,2,3] being mapped against local objects with ids = [1,2].
One of two things could happen now:

1. The local object(id=3) is overwritten.  That is, the ``inProgress`` flag is reset to ``false``
2. A second local object(id=3) is created: https://github.com/SyncDB/Sync/issues/301

Both cases are clearly not what we want.

**Comment by Proper-Job** [comment]
@3lvis You also suggested running the predicate against the incoming JSON.  How would this help in my example above?  The JSON object are missing the ``in_progress`` flag, so none of the JSON objects would get dropped from the JSON payload.

I believe the solution to this conundrum is to employ 2 predicates.

1. An include predicate that fetches a list of local objects that are to be included in mapping operations:  
    1. Local objects in this list that are missing from the JSON are DELETED
    2. JSON objects that are not part of this list are INSERTED
    3. Objects that are in the JSON and in this list are UPDATED

2. An exclude predicate that fetches a list of local objects that are to be excluded from mapping operations. This predicate essentially vetoes operations i and iii from the include predicate.
    1. Local objects in this list that are missing from the JSON are **NOT** DELETED
    2. JSON objects that are not part of this list are **ARE** INSERTED
    3. Objects that are in the JSON and in this list are **NOT** UPDATED

**Comment by Proper-Job** [comment]
Actually come to think of it, I believe it's necessary to split the predicates even further. In some cases it is necessary to differentiate between which objects are to be excluded from UPDATES and which are to be excluded from DELETES.

I can build a use case for this if you like.

Naturally this only becomes necessary once you start changing properties of objects that come from the server.  In read-only situations this fine grained distinction is not necessary.

**Comment by 3lvis** [comment]
Hi @Proper-Job, I think you're right. Thanks for taking the time to explain this.

**Comment by 3lvis** [comment]
@allemattio I would advise that locally the id that you assign to your item is an id that you won't find in the backend. You can either have a local-only id, so you're sure this won't get overwritten, or you can make a fake (remote) id that has low collision rate with the remote one.

**Comment by 3lvis** [comment]
Hopefully this will give a better perspective on how to handle this scenarios.

https://github.com/SyncDB/OfflineCRUDDemo

Let me know if something is unclear.
