### ISSUE TITLE
`Int` getting stored as 0

### ISSUE THREAD

**Issue by AnnieNinaJoyceV** [SyncDB/Sync#302]
![sample-json](https://cloud.githubusercontent.com/assets/7369485/19618181/b5e353a0-9860-11e6-9585-62840f509299.png)

For the above sample `JSON`, I have tried with following 2 core data models.
Where in the first Core Data model, returned `0` for adminId & adminTransactionId and some other String values as `null` (Marked in magenta)

![coredatamodel](https://cloud.githubusercontent.com/assets/7369485/19618184/b88d2bd0-9860-11e6-97b4-b513d746d70f.png)

However after updating to simplified Core data model, solved the `null` string issues but the `0` int issue still persists.

![updated_model](https://cloud.githubusercontent.com/assets/7369485/19618187/c3ebb6a4-9860-11e6-8e1b-4831b1f3542e.png)

**However in both models `resultCode` value was never `0`(i.e returns proper value every time) which is also an `Int`.**

**Code**

_Sync_

> let networkManager = Networking()
>         networkManager.bypassAuthentication()
>         networkManager.fetchFranchiseStores(email: email, password: password) { (result, error) in
>             if error == "" {
>                 let code = result["result_code"].intValue
>                 if code == 200 {
>                     let rDict = result.dictionaryObject
>                     let json = [rDict!]
>                     Sync.changes(json, inEntityNamed: "AdminDetails", dataStack: self.dataStack, completion: { error in
>                         completion(error)
>                     })
>                 }
>             }
>         }

_Fetch_

> let request:NSFetchRequest<NSFetchRequestResult> = NSFetchRequest(entityName: "AdminDetails")
>         let adminDetails = (try! self.dataStack.mainContext.fetch(request)) as! [AdminDetails]
>         if adminDetails.count > 0 {
>             //Take to Home
>             let result = adminDetails[0]
>             print(result.adminTransactionId, result.adminId, result.resultCode)
>         }

Any help is much appreciated to get this fixed. Thanks!

**Comment by 3lvis** [comment]
@AnnieNinaJoyceV check if your Core Data attribute has a default value. Sounds like that's the issue.

**Comment by 3lvis** [comment]
![figure-6](https://cloud.githubusercontent.com/assets/1088217/19618387/66906d4a-9849-11e6-858f-f71318950712.jpg)

**Comment by AnnieNinaJoyceV** [comment]
I tried unchecking the default 0, it still returns 0.
The `resultCode` variable has the same settings and it holds the values just fine.

![default0](https://cloud.githubusercontent.com/assets/7369485/19618602/0847f2f2-986d-11e6-8d38-2b0b7f937e1f.png)

**Comment by 3lvis** [comment]
Can you remove the "Use scalar type"?

**Comment by AnnieNinaJoyceV** [comment]
Unchecking `Use scalar type` returns `nil`.

**Comment by 3lvis** [comment]
\o/

**Comment by 3lvis** [comment]
This is fixed then?!

**Comment by 3lvis** [comment]
http://stackoverflow.com/questions/26977812/should-i-check-the-use-scalar-properties-for-primitive-data-types-when-generat

**Comment by 3lvis** [comment]
@AnnieNinaJoyceV Btw, Sync would normally map to 

`adminTransactionID` instead of `adminTransactionId`
`adminID` instead of `adminId`

**Comment by 3lvis** [comment]
Let me know if there's anything else I can help with.

**Comment by AnnieNinaJoyceV** [comment]
Thanks for the help @3lvis 
I didn't know that `Sync` will automatically map `_id` as `_ID`, that was the error.
