### ISSUE TITLE
Parent entity is ignored when using Sync as NSOperation

### ISSUE THREAD

**Issue by Jonge** [SyncDB/Sync#310]
Hey again @3lvis,

I think I found an issue where by using Sync as NSOperation, the assigned parent entity won't get assigned.

When you change for instance the `testObjectsForParent()` test to use NSOperation, like this:

```
let operation = Sync(changes: objects, inEntityNamed: "SuperNote", predicate: nil, parent: users.first!, context: dataStack.mainContext, dataStack: dataStack)
operation.start()
```

instead of the current:

```
Sync.changes(objects, inEntityNamed:"SuperNote", parent:users.first!, dataStack:dataStack, completion:nil)
```

then the parent will be nil.

Didn't yet dig deeper, so not sure what the issue is here. Or am I doing something wrong?

**Comment by risp** [comment]
I dug a bit deeper and found out that the `parentRelationship` is always set as nil when using an Operation. See here:
https://github.com/SyncDB/Sync/blob/8ae41b52d2fd3f9bb6b6a279d7fe46c3d8e39890/Source/Sync/Sync.swift#L106

And here: https://github.com/SyncDB/Sync/blob/8ae41b52d2fd3f9bb6b6a279d7fe46c3d8e39890/Source/Sync/Sync.swift#L113

**Comment by 3lvis** [comment]
Yeah. Need to refactor a bit to use the same methods.

**Comment by 3lvis** [comment]
Hi @Jonge,

Should be working now :)

**Comment by Jonge** [comment]
@3lvis You're the man! Many thanks! :) Will try it out soon.
