### ISSUE TITLE
newNonMergingBackgroundContext   how?

### ISSUE THREAD

**Issue by jimijon** [SyncDB/Sync#311]
Here is my sample code. I think it is generating the following error:

This application is modifying the autolayout engine from a background thread after the engine was accessed from the main thread. This can lead to engine corruption and weird crashes.

What am I doing wrong?

`        let urlString: String = appDelegate.baseURLString+"_table/news"
        let context = appDelegate.dataStack!.newNonMergingBackgroundContext()
        
        let parameters:Parameters = ["filter":  "lastUpdate > \(stringDate)"]
        let headers = ["X-DreamFactory-API-Key": appDelegate.api_key]
        //parameters["filter"] = "lastUpdate > \(stringDate)"

        
        Alamofire.request(urlString, method: .get, parameters: parameters, headers: headers).responseJSON { response in
            
            switch(response.result) {
            case .success(_):
                context.perform {
                    let data = response.result.value as! [String : AnyObject]
                    if(data["resource"] != nil && (data["resource"]?.count)! > 0){
                        Sync.changes(
                            data["resource"] as! [[String : AnyObject]],
                            inEntityNamed: "News",
                            predicate:nil,
                            parent: nil,
                            inContext: context,
                            dataStack: appDelegate.dataStack!) {
                                error in
                                if(error != nil){
                                    print(error)
                                }
                                
                        }
                    }
                }
                break
                
            case .failure(_):
                print(response.result.error)
                break
                
            }
        }`

**Comment by 3lvis** [comment]
```

**Comment by 3lvis** [comment]
You can use this to check where your app is accessing UI from a background thread.

http://stackoverflow.com/a/32680772/717416
