### ISSUE TITLE
Sync for objective-C (OperationOptions doesn't exist)

### ISSUE THREAD

**Issue by ivoindriksons** [SyncDB/Sync#312]
Hi  @3lvis! 
Lately i have been using Sync in all my projects. Since most of them are in Objective-C i use Sync in objective-C.  I saw that one of the most waited functionality is added from this issue: 
Feature Request to add Update and Delete functions to Sync #162

could you help figure out how i can use in objective-c? 

Here is objective-c example: 

```
[Sync changes:[[responseObject objectForKey:@"data"] objectForKey:@"cards"]
 inEntityNamed:@"Card"
         dataStack:self.dataStack
        completion:^(NSError *error) {
               success(responseObject);
           }];
```

what i would like is: 

```
[Sync changes:[[responseObject objectForKey:@"data"] objectForKey:@"cards"]
        inEntityNamed:@"Card"
            dataStack:self.dataStack
operationOptions:Insert
           completion:^(NSError *error) {
               success(responseObject);
           }];
```

**Comment by 3lvis** [comment]
@ivoindriksons Hi,

The latest version of Sync uses a Swift only API protocol called `OptionSet` for this reason it's not available in Objective-C.

**Comment by 3lvis** [comment]
Do you have any ideas on what we could do there?

**Comment by ivoindriksons** [comment]
Well. This functionality is very useful. 
My idea probably would be to use to typedef

something like: 
`
typedef NS_ENUM(NSInteger, SyncOperations)
{
Insert,
Update,
Delete,
All
};
`

and based on value use the method needed

**Comment by ivoindriksons** [comment]
Since typedef is available on both objective-C and swift, if i remember correctly.

**Comment by ivoindriksons** [comment]
I found some info regarding this could help regarding this implementation: 

In Objective-C: 

```
typedef NS_OPTIONS(NSInteger, FulfillmentOption) {
    FulfillmentOptionPickup = 1 << 0,
    FulfillmentOptionShipping = 1 << 1,
    FulfillmentOptionUserShipping = 1 << 2,
};
```
in an Objective-C header, this would be imported into Swift as

```
public struct FulfillmentOption : OptionSetType {
    public init(rawValue: Int)

    public static var Pickup: FulfillmentOption { get }
    public static var Shipping: FulfillmentOption { get }
    public static var UserShipping: FulfillmentOption { get }
}
```
More Information can be found in the "Using Swift with Cocoa and Objective-C" reference:

"Interaction with C APIs":
Swift also imports C-style enumerations marked with the  NS_OPTIONS macro as a Swift option set. Option sets behave similarly to imported enumerations by truncating their prefixes to option value names.

**Comment by 3lvis** [comment]
Have you seen a framework combining Objective-C and Swift code? As far as I know this is not supported.

**Comment by ivoindriksons** [comment]
http://stackoverflow.com/questions/32530018/accessing-swift-optionsettype-in-objective-c

Here I think is the same problem, and solution on this provided.
What do you think ?

**Comment by 3lvis** [comment]
Maybe we could have a separate API just for Objective-C that used strings instead.

**Comment by 3lvis** [comment]
It doesn't work because you can't have both Objective-C and Swift in the same framework. I think there might be a workaround but I haven't seen any library doing it.

**Comment by ivoindriksons** [comment]
Ok maybe then your provided solution with strings ?

**Comment by ivoindriksons** [comment]
It seems for now i have found workaround. 
I Created Class in Swift, that uses the new operations. And then i used it as a bridge, to use it in objective-C. For now it seems to work. 

Example: 
`public class func syncsData(_ data: [Any], inEntityNamed entityName: String, dataStack: DATAStack, completed:  @escaping (NSError?) -> Void) {
        Sync.changes(data as! Array, inEntityNamed:entityName, dataStack:dataStack, operations:[.Insert, .Update], completion: {error in
            completed(error)
        })
    }
`

**Comment by ivoindriksons** [comment]
```
public class func syncsData(_ data: [Any], inEntityNamed entityName: String, dataStack: DATAStack, completed:  @escaping (NSError?) -> Void) {
        Sync.changes(data as! Array, inEntityNamed:entityName, dataStack:dataStack, operations:[.Insert, .Update], completion: {error in
            completed(error)
        })
    }

```

**Comment by 3lvis** [comment]
👏

**Comment by 3lvis** [comment]
This is the perfect workaround. Closing this issue.
