### ISSUE TITLE
Delete values for missing attributes/relationships

### ISSUE THREAD

**Issue by risp** [SyncDB/Sync#320]
Hi,

First of all thanks for this framework! Before I was using RestKit but this Sync has much cleaner approach. I was wondering about one thing though: if the server doesn't an attribute it seems Sync doesn't set the value to null. So for example, first the server responds with:

```json
[
  {
    "id": 6,
    "name": "Shawn Merrill",
    "email": "shawn@ovium.com",
    "note": {
      "id": 2,
      "text": "Shawn Merril's diary, episode 1"
    }
  }
]
```
Then later on, when I removed the note on the server, the server sends:
```json
[
  {
    "id": 6,
    "name": "Shawn Merrill",
    "email": "shawn@ovium.com",
  }
]
```
As you see, instead of sending note: null it's not sending note at all. In this case Sync doesn't remove the relationship. Is this something that maybe can be configured somewhere or do you have any tips how to handle this situation?

**Comment by risp** [comment]
I just noticed that even when the server is sending null, still the relationship isn't removed. I tried the following 2 cases:

```json
[
  {
    "id": 6,
    "name": "Shawn Merrill",
    "email": "shawn@ovium.com",
    "note": {}
  }
]
```
```json
[
  {
    "id": 6,
    "name": "Shawn Merrill",
    "email": "shawn@ovium.com",
    "note": null
  }
]

**Comment by 3lvis** [comment]
Hi @risp, you need null to clear the relationship. Your second example should work. I'll have a look. 

Thanks for reporting this!

**Comment by risp** [comment]
Hi @3lvis any idea when you have time to look at this?

**Comment by 3lvis** [comment]
Fixed here https://github.com/SyncDB/Sync/pull/324/commits/f6a32e97403530036e53a51e1a0370a9fb451fe8

I'm sorry this took that long. It usually doesn't take much before things are fixed, it's just that things at work have been quite chaotic. Let me know if you have any other issues.

Have a great weekend :)

**Comment by risp** [comment]
@3lvis Thanks a lot!
