### ISSUE TITLE
One-to-many Simplified

### ISSUE THREAD

**Issue by achirkof** [SyncDB/Sync#321]
Hello!

I have api model like this:
**Calendar**
```json
{ 
    "_id" : "BSkZy5xMtfCMtsqFq", 
    "start" : ISODate("2016-11-12T03:00:00.000+0300"), 
    "eventSourceId" : "FowQzznecDMvymf5g", 
    "eventSourceType" : "workout", 
    "title" : "Workout", 
    "color" : "#62cb31", 
    "createdBy" : "uCm7kfF3SJHRsoBrJ", 
    "createdAt" : ISODate("2016-11-12T14:04:32.217+0300"), 
    "isCompleted" : false
}
```

**Workout**
```json
{ 
    "_id" : "FowQzznecDMvymf5g", 
    "workoutName" : "Workout", 
    "workoutDesc" : "<p><br></p>", 
    "workoutExercises" : [],
    "createdBy" : "uCm7kfF3SJHRsoBrJ", 
    "createdAt" : ISODate("2016-11-12T14:04:32.235+0300"), 
    "isPrivate" : true, 
    "isDeleted" : false, 
    "plannedTo" : [
        "BSkZy5xMtfCMtsqFq"
    ]
}
```
**Workout** have simplified relationship to **Calendar**. Field `plannedTo` contains array of `Calendar ids`.

I have Core Data model like this:
![image 2016-11-12 at 2 30 26 pm](https://cloud.githubusercontent.com/assets/1292136/20237484/b3599baa-a8e4-11e6-847d-ce8d9b9c1c4d.png)

Fiels `plannedTo` equal to `Calendar id` and `eventSourceId` equal to `workout id`. 

The problem is **Sync** doesn't fill core data entities.
Calendar entity have empty field `ZEVENTSOURCEID`

![image 2016-11-12 at 2 34 46 pm](https://cloud.githubusercontent.com/assets/1292136/20237531/dc345b22-a8e5-11e6-8ba9-d041d17a086f.png)

and

Workout have no field `ZPLANNEDTO`

![image 2016-11-12 at 2 36 05 pm](https://cloud.githubusercontent.com/assets/1292136/20237511/851f4bee-a8e5-11e6-802d-d8342cd7e485.png)

I don't know how to setup core data model correctly.

**Comment by 3lvis** [comment]
Hi! Could you check if this is related to Sync mapping to ID instead of `Id`?  meaning change `eventSourceId` to `eventSourceID`.

**Comment by 3lvis** [comment]
You might need to change this in the `hyp.remoteKey` as well.

In your Core Data attribute `eventSourceID`
`hyp.remoteKey` =  `eventSourceId`

**Comment by 3lvis** [comment]
Regarding `plannedTo`. I believe that Sync would expect `planned_to_ids` to do an automatic mapping. I don't remember testing this with camelCase. But it should look for `plannedToIDs`. I'll have a closer look when my plane lands.

**Comment by achirkof** [comment]
Hi @3lvis !
I can confirm that if I set field name to `eventSourceID` and `hyp.remoteKey = eventSourceId` for **Calendar** and
`plannedToIDs` for **Workout** field `ZEVENTSOURCEID` filled by workout id's now.

In **Workout** entity there is no new file and I think it is not necessary.

**Comment by 3lvis** [comment]
Awesome! I think is fine to close this issue then. Let me know if anything goes wrong and I'll reopen this one.

Have a great weekend!
