### ISSUE TITLE
Feature Request / Question: A way to change a single object

### ISSUE THREAD

**Issue by neil-morrison44** [SyncDB/Sync#326]
Hi, I've got a single json object coming in from a pubsub stream, it exists in the core data store already.

I'm looking for a way to run all the nice sync relationship syncing things using this json blob and the entity which exists in core data?

**Comment by 3lvis** [comment]
Hi @neil-morrison44,

There isn't such thing at the moment but should be simple to add.

I think it could look something like this.

```swift
func update(_ object: NSManagedObject, with changes: Any, in context: NSManagedObjectContext, completion: ((_ error: NSError?) -> Void)?) {
    context.perform {
        let fetchRequest = NSFetchRequest<NSFetchRequestResult>(entityName: entityName)
        fetchRequest.predicate = NSPredicate(format: "id = %@", object.hyp_primaryKey())
        let object = try! backgroundContext.fetch(fetchRequest).first!
        object.hyp_fill(with: changes)
        do {
            try backgroundContext.save()
            DispatchQueue.main.async {
                completion(nil)
            }        
        } catch let error as NSError {
            DispatchQueue.main.async {
                completion(error)
            }
        }
    }
}
```

**Comment by 3lvis** [comment]
Probably related to https://github.com/SyncDB/Sync/issues/162 as well.

**Comment by neil-morrison44** [comment]
@3lvis I tried something similar, however I'm using JSON  with "*_ids" suffixes, which are dealt with in the NSManagedObject+Sync extension rather than within the hyp_fill method, so that solution works for the basic properties but not the relationships

**Comment by 3lvis** [comment]
@neil-morrison44 `sync_fill` maybe works better there.

**Comment by 3lvis** [comment]
Although that's a private method right now.

**Comment by neil-morrison44** [comment]
@3lvis Yeah, it's that `sync_fillWithDictionary` method I want to be getting at, but since extensions are private to the module in swift there's no way of accessing it (I think, at least?)

**Comment by neil-morrison44** [comment]
@3lvis Any plans to expose this functionality publicly on the Sync class?

**Comment by 3lvis** [comment]
I was wondering what's better

```swift
func update(_ object: NSManagedObject, with changes: Any, in context: NSManagedObjectContext, completion: ((_ error: NSError?) -> Void)?) {
```

vs

```swift
func update(objectWithID id: Any, with changes: Any, in context: NSManagedObjectContext, completion: ((_ error: NSError?) -> Void)?) {
```

**Comment by neil-morrison44** [comment]
Think it needs to be the first one, could be the second one if you also specified the entity name though?

Since id doesn't have to be unique between different entity types, and isn't unique in my case - there's things and comments and users who all share the same id number.

I actually like the 2nd one more since it cuts down on having to do a fetch before it's updated - would move the logic of handling when an update has been requested for a thing that doesn't exist yet into Sync though ( probably just create? )

**Comment by 3lvis** [comment]
Fixed in https://github.com/SyncDB/Sync/pull/332

If you have any feedback regarding the API let me know 🎉

**Comment by neil-morrison44** [comment]
👍  the insertOrUpdate method seems like exactly what I was looking for
