### ISSUE TITLE
To-Many Relationship not relating.

### ISSUE THREAD

**Issue by jimijon** [SyncDB/Sync#339]
I tried syncing first a one-to many. None of the manys were "relate". I went the opposite with using the many linking to the to-one and that worked.

Now I have a large product sync. But my to-ones are written to the database but when I use core data to drill down, the inverse relationship shows nothing.

Don't know what is happening but that my to-many relationships aren't being created in CoreData.

**Comment by 3lvis** [comment]
@jimijon Hi James,

Could you share your Core Data model and also the JSON that you're using. Before being able to help you I need to reproduce the issue. :)

Thanks!

**Comment by jimijon** [comment]
Might be red-herring…. I changed my sync call and removed Operations. This is seemingly causing records to be created and then deleted.
I guess I don’t understand how those operations work. I am setting it back to insert and update explicitly.




 <http://www.jimijon.com/>		
James Cicenia
Founder / CEO
Direct: (773) 398-4649
Mail: james@jimijon.com
 <http://www.linkedin.com/profile/view?id=4226928&trk=tab_pro>

**Comment by jimijon** [comment]
hmmm now I am getting some random crash.





 <http://www.jimijon.com/>		
James Cicenia
Founder / CEO
Direct: (773) 398-4649
Mail: james@jimijon.com
 <http://www.linkedin.com/profile/view?id=4226928&trk=tab_pro>

**Comment by jimijon** [comment]
{
	"resource": [{
		"id": "2148",
		"upc": "678523040102",
		"nfCode": "zq30f",
		"plu": "PLU",
		"vlu": "VLU",
		"brandNFCode": "0719",
		"shelfCategoryId": "413",
		"sectionKey": "P",
		"productName": "Pretzel Stick",
		"productDescription": "Pretzel Stick",
		"packageType": "Bag",
		"packageSize": "14.1",
		"packageUOM": "oz",
		"ingredients": "Corn Starch, Potato Starch, Rice Flour, Soluble Corn Fiber, Pal Oil, Sugar, Salt, Cellulose Gum, Soy Lecithin, Yeast Extract, Sodium Bicarbonate, Sodium Acid Pyrophosphate, Citric Acid.",
		"productUrl": "",
		"imageSmallUrl": "",
		"imageLargeUrl": "",
		"disLikeCount": 0,
		"likeCount": 0,
		"glutenFreeYN": "Y",
		"deleteYN": "N",
		"hasCouponYN": "",
		"isHighlightedYN": "",
		"origin": null,
		"originProductId": null,
		"lastUpdate": "2016-10-28 14:56:14",
		"glutenFreeCertYN": null,
		"glutenFreeCert": null,
		"organicYN": null,
		"organiCertYN": null,
		"organicCert": null,
		"gmoYN": null,
		"gmoCert": null,
		"fairTradeYN": null,
		"kosherYN": null,
		"halalYN": null,
		"dairyYN": null,
		"lactoseFreeYN": null,
		"sugarFreeYN": null,
		"hfcsFreeYN": null,
		"cornFreeYN": null,
		"soyFreeYN": null,
		"veganYN": null,
		"vegetarianYN": null,
		"shelfCategory": {
			"id": "413",
			"shelfId": "1",
			"sectionKey": "P",
			"shelfCategoryDesc": "Pretzels",
			"productCount": 23,
			"originUpdate": null,
			"deleteYN": "N",
			"lastUpdate": "2016-11-22 16:18:01",
			"shelfCategoryNFCode": null
		},
		"brand": {
			"id": "167",
			"nfCode": "0719",
			"manufacturerNFCode": "mnfcode",
			"sectionKey": "G",
			"brandName": "Glutino",
			"glutenFreeCount": 0,
			"productCount": 91,
			"deleteYN": "N",
			"lastUpdate": "2016-11-22 16:18:01"
		}
	}, {
		"id": "2149",
		"upc": "678523038444",
		"nfCode": "6cjn6",
		"plu": "PLU",
		"vlu": "VLU",
		"brandNFCode": "0719",
		"shelfCategoryId": "524",
		"sectionKey": "C",
		"productName": "Crackers - Cheddar",
		"productDescription": "Crackers",
		"packageType": "Box",
		"packageSize": "4.4",
		"packageUOM": "oz",
		"ingredients": "Corn Starch, White Rice Flour, Organic Palm Oil, Modified Corn Starch, Cheese Preparation (mix Of Gouda, Cheddar And Camembert Cheese Powder [milk, Salt, Starter Cultures, Rennet, Annatto And Beta-carotene For Colour, Cheese Cultures], Sodium Citrate, Salt), Dextrose, Sunflower Lecithin, Eggs, Sunflower Lecithin, Natural Flavor, Dextrose, Sugar, Salt, Guar Gum, Sodium Bicarbonate, Ammonium Bicarbonate.",
		"productUrl": "",
		"imageSmallUrl": "",
		"imageLargeUrl": "",
		"disLikeCount": 0,
		"likeCount": 0,
		"glutenFreeYN": "Y",
		"deleteYN": "N",
		"hasCouponYN": "",
		"isHighlightedYN": "",
		"origin": null,
		"originProductId": null,
		"lastUpdate": "2016-10-28 14:56:14",
		"glutenFreeCertYN": null,
		"glutenFreeCert": null,
		"organicYN": null,
		"organiCertYN": null,
		"organicCert": null,
		"gmoYN": null,
		"gmoCert": null,
		"fairTradeYN": null,
		"kosherYN": null,
		"halalYN": null,
		"dairyYN": null,
		"lactoseFreeYN": null,
		"sugarFreeYN": null,
		"hfcsFreeYN": null,
		"cornFreeYN": null,
		"soyFreeYN": null,
		"veganYN": null,
		"vegetarianYN": null,
		"shelfCategory": {
			"id": "524",
			"shelfId": "17",
			"sectionKey": "C",
			"shelfCategoryDesc": "Cheese & Peanut Butter",
			"productCount": 7,
			"originUpdate": null,
			"deleteYN": "N",
			"lastUpdate": "2016-11-22 16:18:01",
			"shelfCategoryNFCode": null
		},
		"brand": {
			"id": "167",
			"nfCode": "0719",
			"manufacturerNFCode": "mnfcode",
			"sectionKey": "G",
			"brandName": "Glutino",
			"glutenFreeCount": 0,
			"productCount": 91,
			"deleteYN": "N",
			"lastUpdate": "2016-11-22 16:18:01"
		}
	}
 <http://www.jimijon.com/>		
James Cicenia
Founder / CEO
Direct: (773) 398-4649
Mail: james@jimijon.com
 <http://www.linkedin.com/profile/view?id=4226928&trk=tab_pro>

**Comment by jimijon** [comment]
Maybe my extensive use of my own named primary keys?

**Comment by 3lvis** [comment]
Could you share your Core Data model as well? Also would be nice to know in which places you're using custom user info attributes.

**Comment by jimijon** [comment]
Rolled back to 3.2.4 and it is working again. 
I had sent the model with the JSON. Did you not get it?

**Comment by 3lvis** [comment]
Nope, no model. https://github.com/SyncDB/Sync/issues/339

**Comment by jimijon** [comment]
did you get the model? Plus the custom user info attributes are in "nfCode"

**Comment by 3lvis** [comment]
Hi James, there's no model here, something must be going on with GitHub.

**Comment by 3lvis** [comment]
Could you try adding it using the web client instead of through email? Maybe that was the problem.

**Comment by jimijon** [comment]
send me your email… I attached it both as the model and as a zip file.


 <http://www.jimijon.com/>		
James Cicenia
Founder / CEO
Direct: (773) 398-4649
Mail: james@jimijon.com
 <http://www.linkedin.com/profile/view?id=4226928&trk=tab_pro>

**Comment by jimijon** [comment]
Ever get the model? Would love to upgrade.

**Comment by 3lvis** [comment]
@jimijon I got your model, but I am crazy busy at work. I'll see if I can get try it out this weekend :)

**Comment by jimijon** [comment]
Understood. The older version is working fine. Just releasing a new version of the app to the store next week.

What is new in 4 anyway?



 <http://www.jimijon.com/>		
James Cicenia
Founder / CEO
Direct: (773) 398-4649
Mail: james@jimijon.com
 <http://www.linkedin.com/profile/view?id=4226928&trk=tab_pro>

**Comment by 3lvis** [comment]
@jimijon Some bug fixes, mainly for `to-one` relationships using only the id. Like a user that links to a company using `company_id`. And a fix for syncing ordered `to-many` relationships.

https://github.com/SyncDB/Sync/releases/tag/2.4.0

**Comment by 3lvis** [comment]
Gave it a try, seems like everything is working as it should, let me know if I'm missing something.

https://github.com/SyncDB/Sync/pull/349

**Comment by jimijon** [comment]
What did you find?
 <http://www.jimijon.com/>		
James Cicenia
Founder / CEO
Direct: (773) 398-4649
Mail: james@jimijon.com
 <http://www.linkedin.com/profile/view?id=4226928&trk=tab_pro>

**Comment by 3lvis** [comment]
@jimijon Have a look here -> https://github.com/SyncDB/Sync/pull/349

**Comment by jimijon** [comment]
I will try next week… this week we are pushing.


 <http://www.jimijon.com/>		
James Cicenia
Founder / CEO
Direct: (773) 398-4649
Mail: james@jimijon.com
 <http://www.linkedin.com/profile/view?id=4226928&trk=tab_pro>

**Comment by 3lvis** [comment]
@jimijon Let me know how it goes. Good luck on the new release. ❤️

**Comment by jimijon** [comment]
Thanks and will do.

 <http://www.jimijon.com/>		
James Cicenia
Founder / CEO
Direct: (773) 398-4649
Mail: james@jimijon.com
 <http://www.linkedin.com/profile/view?id=4226928&trk=tab_pro>

**Comment by jimijon** [comment]
Not quite.


 <http://www.jimijon.com/>		
James Cicenia
Founder / CEO
Direct: (773) 398-4649
Mail: james@jimijon.com
 <http://www.linkedin.com/profile/view?id=4226928&trk=tab_pro>
