### ISSUE TITLE
Swift 3 and Xcode 8 Codegen Class Definition model objects seem not to get stored

### ISSUE THREAD

**Issue by jim-dev2rights** [SyncDB/Sync#354]
Seeing a strange issue that for the life of me i can't see what is causing it. 

It appears Sync.changes fails When calling DATAFilter.changes gets called. 

It appears that 

`let primaryKeysAndObjectIDs = context.managedObjectIDs(in: entityName, usingAsKey: localPrimaryKey, predicate: predicate) as [NSObject: NSManagedObjectID]`

Always returns an empty dictionary and thus nothing gets written to the DB. With the params:

`in: Flibble, usingAsKey: cache_key, predicate: nil`

Where Flibble is in my .xcdatamodeld and has a primary key value set for cache_key.

I tested the DATAStack by manually writing the data to disk to make sure that the issue was not with the stack. 

context is not nil either. 

I would love to know if this has been seen before as it fails silently. Ill look into it a bit more but maybe there is a gotcha i'm missing?

**Comment by 3lvis** [comment]
Hi @jim-dev2rights,

I think this could be related to many-to-many relationships, if you have an array of objects that references another element inside, you need to make sure that the referenced object already exists in the database. The easiest way is just by making sure that your JSON doesn't have references to other objects but instead it sends the full object.

I hope I explained myself well. I know it took a long time before I could reply to this issue. Gonna close this for now if you need any help you can also contact me on Gitter. https://gitter.im/SyncDB/Sync
