### ISSUE TITLE
Update reserved attributes link

### ISSUE THREAD

**Issue by RJiryes** [SyncDB/Sync#355]
Great library guys, thanks!  Please update the reserved attributes link in the read me file as it is not working anymore. I've spent an hour trying to figure out a problem, and figured that it was probably a reserved attribute.  

Thanks! 👍

**Comment by 3lvis** [comment]
Thanks for reporting this issue Ramzi. 💐 

It was fixed here: https://github.com/SyncDB/Sync/commit/0ca78cdc488f963cc5ea78258c9db8f4e38c1bd4
