### ISSUE TITLE
infinite loop in hyp_dictionary() with relationships

### ISSUE THREAD

**Issue by ArdentZeal** [SyncDB/Sync#368]
Hello I am new to sync and started implementing the basics.

I ran into a problem I do not know how to fix.
If I use of of my NSManagedobjects and call .hyp_dictionary() on it and it does not have a relationship, I get a perfect JSON response. As soon as I add a relationship to it and call .hyp_dictionary() again, I get an infinity loop and a corresponding crash after 13xxx calls.

I suspected a wrong primary key setup, so i used id with hyper.isPrimaryKey = true and hyper.remoteKey = id. 
That did not work so I switched to using uuid  with hyper.isPrimaryKey = true, but also to no avail.

I am kind of stumped how to proceed further. 

Any help would be appreciated. I attached my Core Data models below.

Kind Regards

![image](https://cloud.githubusercontent.com/assets/5508364/22831557/12ba3e62-efab-11e6-9bc9-2f062a9da547.png)

**Comment by ArdentZeal** [comment]
I think it might be the same issue described here.

https://github.com/SyncDB/SYNCPropertyMapper/issues/93

Sadly there is no solution in the closed thread.

**Comment by 3lvis** [comment]
@ArdentZeal Hi,

Are you calling `hyp_dictionary` for Task, Tag or MapLocation? I'll try reproducing your issue.

I remember seeing something regarding infinite loops here: https://github.com/SyncDB/SYNCPropertyMapper/issues/112

The solution was to add a "hyper.nonExportable" flag to the relationship. https://github.com/SyncDB/SYNCPropertyMapper#excluding

**Comment by ArdentZeal** [comment]
I did try all 3, and everything failed. Thanks for looking into this.

**Comment by ArdentZeal** [comment]
Hey 3lvis,

The solution was to add a "hyper.nonExportable" flag to the relationship. 

This was the problem, the solution above is working.

Thank you very much.

**Comment by 3lvis** [comment]
@ArdentZeal Great to hear. I'll add to the FAQ.

**Comment by 3lvis** [comment]
Added! https://github.com/SyncDB/Sync/blob/master/README.md#infinite-loop-in-hyp_dictionary-with-relationships
