### ISSUE TITLE
Progress Delegate

### ISSUE THREAD

**Issue by eman8519** [SyncDB/Sync#371]
There doesn't seem to be a way to get progress updates for syncing.  I have a very large dataset that I'm syncing from, and I would like to provide user feedback on the syncing status.  I will be happy to work on this feature, but before doing so I want to be sure that I'm not missing an obvious way of doing this.

**Comment by 3lvis** [comment]
Hi @eman8519,

Not sure if this fixes your issue but you could use Core Data's notification system to be notified of progress.

https://github.com/SyncDB/Sync#logging-changes

**Comment by eman8519** [comment]
Thanks @3lvis I will close this for now, and perhaps use the above mentioned as a base for a progress handler I may add in the future (if it is even possible).  I dug in a bit more and found some bottle necks in the DATAFilter class that I've submitted a PR for I have plans to further optimize that class when I have a little more spare time to work on it.  Thank you for your response.
