### ISSUE TITLE
Sync with given parent entity does not success!!

### ISSUE THREAD

**Issue by jetstar89** [SyncDB/Sync#372]
Hi 3lvis,
I tried to sync my changes with given parent entity but It doesn't success.
Could you update the example?

**Comment by 3lvis** [comment]
Hi Huy!

That's strange, got the unit test working fine.

https://github.com/SyncDB/Sync/blob/master/Tests/Sync/SyncTests.swift#L242-L269

**Comment by jetstar89** [comment]
This is my code
`self.dataStack.performInNewBackgroundContext({ (context) in
                if let parent = ParentEntity.extFind(in: context, by: itemId) {
                    Sync.changes(change, inEntityNamed: "ChildEntity", predicate: nil, parent: parent, inContext: context, completion: { (error) in
                        if error != nil {
                            completion(Result.failure(error))
                        } else {
                            completion(Result.success(true))
                        }
                    })
                }
            })`
After that, I saw ChildEntity insert/update but its parent entity is not linked.

**Comment by 3lvis** [comment]
@jetstar89 Could you try doing it this way?

https://github.com/SyncDB/Sync/blob/master/Tests/Sync/SyncTests.swift#L242-L269

Meaning get the parent in the main context, then use the method

```swift
Sync.changes(objects, inEntityNamed: "SuperNote", parent: users.first!, dataStack: dataStack, completion: nil)
```

**Comment by jetstar89** [comment]
thanks 3lvis,
I tried, and It works when using main context. But I wonder why it doesn't work when using background context?

**Comment by yonat** [comment]
@3lvis I encountered a similar problem, but it was not solved by using the main context. Instead, I found that Sync expects the child objects JSON to contain a `<parent>_id` field. I think that's probably a mistake, no?

Anyway, I use this workaround:

```swift
extension NSManagedObject {
    func syncChildren(changes: [[String: Any]], inEntityNamed: String, predicate: NSPredicate? = nil, completion: ((NSError?) -> Void)?) {
        var changes = changes
        if nil != entity.attributesByName["id"], let syncID = value(forKey: "id") {
            let parentIDAttribute = entity.name!.snakeCased() + "_id"
            for i in 0 ..< changes.count {
                changes[i][parentIDAttribute] = syncID
            }
        }
        managedObjectContext?.sync(changes, inEntityNamed: inEntityNamed, predicate: predicate, parent: self, completion: completion)
    }
}

extension String {
    func snakeCased() -> String {
        return try! NSRegularExpression(pattern: "([a-z])([A-Z])").stringByReplacingMatches(in: self, range: NSMakeRange(0, count), withTemplate: "$0_$1").lowercased()
    }
}

```

**Comment by 3lvis** [comment]
Hi @yonat!

Interesting workaround, would you mind sharing a little bit more of your use case? How does the child JSON and parent JSON look like? I would be happy to include your case as a unit test to make sure we support that case in the future!

**Comment by yonat** [comment]
Thanks for responding!

My use case:
I have separate server requests for each type of entity. So for the parent I may get:

```json
[
  {
    "name": "secret",
    "id": "6"
  }
]
```

Then I send a separate request to get 6's children, and the response would be something like:

```json
[
  {
    "email": "james@mi6.gov.uk",
    "id": "007"
  }
]
```

So the parent's JSON does not include its children IDs, and the children's JSON does not include they're parent ID.

(I can't change the server code, have to use what already exists.)

Thanks for this great package!

**Comment by 3lvis** [comment]
Thanks for the extra info! I'll hope to have some time to reproduce it :)

**Comment by yonat** [comment]
Just bumped into another issue:

Syncing children of one parent, deletes the children of all other parents.
So now my workaround looks like this:

```swift
    func syncChildren(changes: [[String: Any]], inEntityNamed child: String, predicate: NSPredicate? = nil, completion: ((NSError?) -> Void)?) {

        // ensure children are explicitly related to their parent
        var changes = changes
        if nil != entity.attributesByName["id"], let syncID = value(forKey: "id") {
            let parentIDAttribute = entity.name!.snakeCased() + "_id"
            for i in 0 ..< changes.count {
                changes[i][parentIDAttribute] = syncID
            }
        }

        // don't delete children of other parents
        var predicate = predicate
        if let parentRelationName = NSEntityDescription.entity(forEntityName: child, in: managedObjectContext!)?.relationships(forDestination: entity).first?.name
        {
            let childPredicate = NSPredicate(format: "\(parentRelationName) = %@", self)
            predicate = nil == predicate ? childPredicate : NSCompoundPredicate(andPredicateWithSubpredicates: [predicate!, childPredicate])
        }

        managedObjectContext?.sync(changes, inEntityNamed: child, predicate: predicate, parent: self, completion: completion)
    }
}

extension String {
    func snakeCased() -> String {
        return try! NSRegularExpression(pattern: "([a-z])([A-Z])").stringByReplacingMatches(in: self, range: NSMakeRange(0, count), withTemplate: "$0_$1").lowercased()
    }
}
```
