### ISSUE TITLE
JSON:API Support

### ISSUE THREAD

**Issue by markst** [SyncDB/Sync#376]
Is it possible to use JSON:API formatted responses for mapping?
jsonapi.org

**Comment by padlocked17** [comment]
I don't see any reason why not.  It looks very straight-forward and super clean.  I wish the JSON that I was being served looked that nice.

**Comment by markst** [comment]
Perhaps this issue is more appropriate for https://github.com/SyncDB/SYNCPropertyMapper

**Comment by markst** [comment]
I suppose it wouldn't be too complicated to implement. 

I'd need to check for nested `attributes` as follows:
```swift
hyp_fill(with: dictionary)
if let attributes = dictionary["attributes"] as? [String:Any] {
    hyp_fill(with: attributes)
}
```

`SYNCPropertyMapper` would need to support hyphenated-case else I'd have to add all remote keys for multi word attributes. 

First pass would have to map the attributes of the objects `relationships` to provide the linkage for the `included` which would have to be mapped on second pass & synced...

**Comment by 3lvis** [comment]
Hi @markst,

We don't have support for it out of the box, adding support for it doesn't seem like a bad idea, though. Sadly, all the APIs that I've used don't use that, that's the main reason it hasn't been prioritized.

**Comment by 3lvis** [comment]
Gonna be closing this for now, unless someone else is willing to work on it I don't think it's happening.
