### ISSUE TITLE
Sync 2.* Warnings

### ISSUE THREAD

**Issue by dneykov** [SyncDB/Sync#396]
Hi,
is it possible to fix Xcode 8.3 warnings for Sync 2 also. Because my deployment target is 8.0 and I cannot update to Sync 3

Remark: There is mistake in Sync 3 README. It says iOS 8.0 or above but in podspec file min is iOS 9.0

Thanks.

**Comment by 3lvis** [comment]
@dneykov Updated, now it says iOS 9.

**Comment by dneykov** [comment]
That was quick :)
If I have time I can make PR to fix the warnings in 2.*

**Comment by dneykov** [comment]
I cannot use 2.7.1 because it requires iOS 9.0.
I thought iOS 9.0 is required for Sync 3+

**Comment by 3lvis** [comment]
One sec changing 3.* to be iOS 8.

**Comment by dneykov** [comment]
This is awesome.
I never had so quick response on GitHub :)

**Comment by 3lvis** [comment]
Ready!

https://github.com/SyncDB/Sync/releases/tag/3.2.2
