### ISSUE TITLE
Cannot sync doubles

### ISSUE THREAD

**Issue by dneykov** [SyncDB/Sync#402]
Sometimes doubles are returning nil here is an example of JSON

```
{
    "id": "495fa6ef6161ea2ed0d445e70eff38e5",
    "number": "045349",
    "name": "Vloeddijk 244",
    "lat": 52.557335755104,
    "lon": 5.9157470378042
}
```

In Core Data are Double and in the model are NSNumber?
Sometimes both are nil sometimes just "lon" nil
Thanks

**Comment by dneykov** [comment]
Never mind I was checking before sync completion

**Comment by 3lvis** [comment]
I'm glad you got this working :)
