### ISSUE TITLE
Cannot convert value of type 'DATAStack' to expected argument type 'DataStack'

### ISSUE THREAD

**Issue by jay-cohen** [SyncDB/Sync#404]
Trying to performa sync operation and getting the following error:
`Cannot convert value of type 'DATAStack' to expected argument type 'DataStack`

```
Sync.changes(data["stations"] as! [[String : Any]], inEntityNamed: "localList", dataStack: coreDataStack) { error in
completion(error)
}
```

Initializing the dataStack as follows:
`var coreDataStack: DATAStack = DATAStack(modelName: "database")`

**Comment by jay-cohen** [comment]
Managed to solve it - DATAStack not needed as an import

**Comment by 3lvis** [comment]
<3 I'm glad you got it working
