### ISSUE TITLE
Set operations in Objective-C

### ISSUE THREAD

**Issue by lm2343635** [SyncDB/Sync#406]
How can I set operations: [.insert, .update] in Objective-C
```swift
Sync.changes(secondImport, inEntityNamed: "User", dataStack: dataStack, operations: [.insert, .update]) {
    // Likely after some changes have happened, here usually Sync would remove the not found items but this time
    // new users have been imported, existing users have been updated, and not found users have been ignored
}
```
I mean I want to use this method in Objective-C, but I cannot find it. @3lvis

**Comment by 3lvis** [comment]
Hi @lm2343635,

It's using OptionSet which isn't available in Objective-C. We would have to make a bridge API using Objective-C enums and methods that can be accessed on Objective-C. Shouldn't be hard to make, I can see if I have time next week but I can't promise anything, if you're willing to work on it, it would be very nice!

Here's where the enum is defined. https://github.com/SyncDB/Sync/blob/master/Source/Sync/Sync.swift#L19-L30

```swift
Sync.objc_changes(secondImport, inEntityNamed: "User", dataStack: dataStack, operations: {objc_enums}) {
    // Likely after some changes have happened, here usually Sync would remove the not found items but this time
    // new users have been imported, existing users have been updated, and not found users have been ignored
}
```


I'm thinking a Swift file with

**Comment by lm2343635** [comment]
Thank you for you replying. I've solve this problem in such way:
https://github.com/lm2343635/Grouper/blob/2bdb6c113a36fcffd5f77d526bb03067661b2787/Core/Support/Sync%2BObjC.swift
But I do not think it is a good solution to this problem. 
I have know what you said. I am very pleasure to make a transfer file using enums in Objective-C. I will make a pull request to you.(^ . ^)
Best wishes.

**Comment by lm2343635** [comment]
New pull request has been submitted. @3lvis

**Comment by 3lvis** [comment]
Fixed on https://github.com/SyncDB/Sync/releases/tag/3.3.0, still needs a CocoaPods release.

**Comment by lm2343635** [comment]
Cloud you please release 3.3 on CocoaPods. Thanks!

**Comment by 3lvis** [comment]
Need to wait until I arrive home, this computer doesn't have CocoaPods trunk set up.

**Comment by 3lvis** [comment]
Ready on CocoaPods!
