### ISSUE TITLE
one-to-many relationships don't work

### ISSUE THREAD

**Issue by ValeriiVV** [SyncDB/Sync#409]
SOLVED
Hey all, I can't get an access to any of my one-to-many relationships... The server sends me normal JSON, but after I've saved it via SyncDB - I'm trying to get an access to relationships, but they are always = nil
These are my attached files:
1. My Schema
2. My JSON-response
3. Printed out product that I fetched from Core Data (as you can see - all relationships are faulted)
4. Printed out TAGS in every product (I send product from ViewController to UITableViewCell and then, in didSet I'm trying to get an access to certain property)
5. My code, that receive data from server via Alamofire and then save it to Core data via SyncDB.

<img width="1382" alt="1" src="https://user-images.githubusercontent.com/27637520/27741757-36c98800-5dc7-11e7-85ad-121a1f0c5d94.png">

![2017-06-30 18 07 30](https://user-images.githubusercontent.com/27637520/27741839-7365f384-5dc7-11e7-8270-c42140609120.png)

<img width="408" alt="3" src="https://user-images.githubusercontent.com/27637520/27741759-36f227b0-5dc7-11e7-8132-3468da590569.png">
<img width="702" alt="4" src="https://user-images.githubusercontent.com/27637520/27741758-36f1976e-5dc7-11e7-8908-6bc4ec34ac13.png">
<img width="811" alt="5" src="https://user-images.githubusercontent.com/27637520/27741760-36f31f4e-5dc7-11e7-8cb8-565950f0b616.png">

Help me please, I've been trying to make it work for 3 days)

**Comment by ValeriiVV** [comment]
SOLVED:
The reason was that I named my attribute "tag_id" (like in my json response), but I should had named it "tagID".

**Comment by 3lvis** [comment]
I'm glad you got it working @ValeriiVV! Sorry for the late response :)
